import { DrugInteraction } from './types';

export const INITIAL_30_INTERACTIONS: Omit<DrugInteraction, 'id'>[] = [
  {
    drugA: 'Warfarina',
    drugB: 'Aspirina (Ácido Acetilsalicílico)',
    synonymsA: ['Marevan', 'Coumadin'],
    synonymsB: ['AAS', 'Aspirina Prevent', 'Somalgin'],
    severity: 'Grave',
    category: 'Cardiologia / Hematologia',
    mechanism: 'Efeito aditivo na inibição da agregação plaquetária e anticoagulação oral, somado ao dano na mucosa gástrica provocado pelo AAS.',
    effect: 'Risco extremamente elevado de hemorragia gastrointestinal, hematomas espontâneos e sangramentos intracranianos potencialmente letais.',
    recommendation: 'Evitar associação desnecessária. Se estritamente indispensável (ex: prótese valvar cardíaca recente), monitorar INR frequentemente e prescrever gastroproteção com Inibidor de Bomba de Prótons (IBP).',
    alternatives: 'Substituição do analgésico por Paracetamol em doses baixas (< 2g/dia) ou Dipirona sob supervisão.',
    foodInteractions: 'Alimentos ricos em Vitamina K (espinafre, couve, brócolis) diminuem a eficácia da Warfarina. Evitar álcool.',
    riskScore: 10,
    affectedOrgans: ['Sistema Cardiovascular', 'Trato Gastrointestinal', 'Cérebro']
  },
  {
    drugA: 'Sinvastatina',
    drugB: 'Claritromicina',
    synonymsA: ['Zocor', 'Vaslip'],
    synonymsB: ['Klaricid', 'Claritron'],
    severity: 'Grave',
    category: 'Cardiologia / Infectologia',
    mechanism: 'A Claritromicina é um potente inibidor da enzima hepática CYP3A4, responsável pelo metabolismo da Sinvastatina.',
    effect: 'Elevação drástica dos níveis plasmáticos de Sinvastatina, podendo deflagrar miopatia grave, rabdomiólise (destruição muscular) e insuficiência renal aguda.',
    recommendation: 'Suspender temporariamente a Sinvastatina durante o tratamento curto com Claritromicina, ou utilizar antibiótico alternativo que não iniba CYP3A4.',
    alternatives: 'Azitromicina (como opção de macrolídeo) ou Rosuvastatina/Pravastatina (estatinas não dependentes estritamente de CYP3A4).',
    foodInteractions: 'Suco de toranja (Grapefruit) inibe CYP3A4 e deve ser evitado absolutamente.',
    riskScore: 9,
    affectedOrgans: ['Musculatura Esquelética', 'Rins', 'Fígado']
  },
  {
    drugA: 'Fluoxetina',
    drugB: 'Tramadol',
    synonymsA: ['Prozac', 'Daforin'],
    synonymsB: ['Dorflex Uno', 'Tramal', 'Sylador'],
    severity: 'Grave',
    category: 'Psiquiatria / Neurologia',
    mechanism: 'Ambos aumentam a atividade serotoninérgica no SNC. Além disso, a Fluoxetina inibe a CYP2D6, impedindo a conversão do Tramadol em seu metabólito analgésico ativo.',
    effect: 'Risco de Síndrome Serotoninérgica (hipertermia, rigidez muscular, tremores, convulsões, instabilidade autonômica) e perda de alívio da dor.',
    recommendation: 'Não associar. Preferir analgesia com mecanismo não serotoninérgico ou ajustar medicação antidepressiva.',
    alternatives: 'Dipirona, Paracetamol ou AINEs de curto prazo para controle analgésico.',
    foodInteractions: 'Evitar suplementos com L-Triptofano e bebidas alcoólicas.',
    riskScore: 9,
    affectedOrgans: ['Sistema Nervoso Central', 'Cérebro']
  },
  {
    drugA: 'Metformina',
    drugB: 'Contraste Iodado Radiológico',
    synonymsA: ['Glucophage', 'Glifage'],
    synonymsB: ['Contraste para Tomografia', 'Iohexol', 'Iodixanol'],
    severity: 'Grave',
    category: 'Endocrinologia / Radiologia',
    mechanism: 'O contraste iodado pode induzir disfunção renal temporária, levando ao acúmulo sistêmico de Metformina.',
    effect: 'Desenvolvimento de Acidose Láctica grave, uma complicação metabólica com taxa de mortalidade superior a 30%.',
    recommendation: 'Suspender a Metformina no dia ou 48h antes do exame de imagem contrastado e retomar apenas 48h após o procedimento, mediante confirmação da função renal normal.',
    alternatives: 'Insulinoterapia de transição caso haja hiperglicemia acentuada no período.',
    foodInteractions: 'Jejum prolongado e desidratação aumentam severamente o risco.',
    riskScore: 9,
    affectedOrgans: ['Rins', 'Sangue (pH metabólico)']
  },
  {
    drugA: 'Enalapril',
    drugB: 'Espironolactona',
    synonymsA: ['Renitec', 'Enalabal'],
    synonymsB: ['Aldactone', 'Di顺actone'],
    severity: 'Grave',
    category: 'Cardiologia / Nefrologia',
    mechanism: 'Tanto o iECA (Enalapril) quanto o diurético poupador de potássio (Espironolactona) reduzem a excreção renal de Potássio.',
    effect: 'Hipercalemia severa (K+ > 6.0 mEq/L), capaz de desencadear bloqueios cardíacos e arritmias fatais como fibrilação ventricular.',
    recommendation: 'Se necessário em insuficiência cardíaca refratária, utilizar doses baixas de Espironolactona (12.5–25mg) com dosagem frequente de eletrólitos e creatinina.',
    alternatives: 'Diuréticos de alça (Furosemida) quando o objetivo for estritamente a depleção de volume.',
    foodInteractions: 'Evitar substitutos do sal contendo cloreto de potássio e consumo excessivo de bananas/abacate.',
    riskScore: 8,
    affectedOrgans: ['Coração', 'Rins']
  },
  {
    drugA: 'Ibuprofeno',
    drugB: 'Paracetamol',
    synonymsA: ['Alivium', 'Advil', 'Artril'],
    synonymsB: ['Tylenol', 'Dorflex (componente)'],
    severity: 'Moderada',
    category: 'Clínica Geral / Analgesia',
    mechanism: 'Uso concomitante em doses elevadas e contínuas sobrecarrega as vias de eliminação renal e hepática.',
    effect: 'Aumento do estresse gastrointestinal e risco de nefrotoxicidade em uso prolongado.',
    recommendation: 'Uso alternado e intercalado em esquema temporário (ex: de 4 em 4 horas alternando os fármacos) é aceitável por curto período (até 3 dias). Evitar sobredosagem combinada.',
    alternatives: 'Compressas térmicas, analgésicos simples em monoterapia.',
    foodInteractions: 'Álcool amplifica a hepatotoxicidade do Paracetamol.',
    riskScore: 5,
    affectedOrgans: ['Fígado', 'Rins', 'Estômago']
  },
  {
    drugA: 'Omeprazol',
    drugB: 'Clopidogrel',
    synonymsA: ['Losec', 'Peprazol'],
    synonymsB: ['Plavix', 'Iscover'],
    severity: 'Moderada',
    category: 'Gastroenterologia / Cardiologia',
    mechanism: 'O Omeprazol inibe fortemente a enzima CYP2C19, necessária para biotransformar o pró-fármaco Clopidogrel em seu formato ativo.',
    effect: 'Redução significativa da ação antiplaquetária do Clopidogrel, aumentando risco de reinfarto ou trombose de stent coronariano.',
    recommendation: 'Substituir o Omeprazol por um protetor gástrico com pouca ou nenhuma inibição do CYP2C19.',
    alternatives: 'Pantoprazol ou Rabeprazol como IBPs alternativos, ou Bloqueadores H2 como Famotidina.',
    foodInteractions: 'Sem interações alimentares diretas relevantes.',
    riskScore: 7,
    affectedOrgans: ['Sistema Vascular', 'Coração']
  },
  {
    drugA: 'Anlodipino',
    drugB: 'Sildenafil',
    synonymsA: ['Pressat', 'Nicorandil'],
    synonymsB: ['Viagra', 'Pramil', 'Cialis (Tadalafila)'],
    severity: 'Moderada',
    category: 'Cardiologia / Urologia',
    mechanism: 'Somatório de vasodilatação arterial sistêmica através do bloqueio de canais de cálcio e inibição da PDE-5.',
    effect: 'Queda acentuada da pressão arterial (hipotensão ortostática), tontura, síncope e dor de cabeça pulsátil.',
    recommendation: 'Iniciar Sildenafil na menor dose possível (25mg) e orientar o paciente a levantar-se devagar após o uso.',
    alternatives: 'Ajuste de dosagem sob supervisão cardiológica.',
    foodInteractions: 'Evitar consumo de bebidas alcoólicas simultâneas para não piorar a hipotensão.',
    riskScore: 6,
    affectedOrgans: ['Pressão Arterial', 'Cérebro']
  },
  {
    drugA: 'Ciprofloxacino',
    drugB: 'Hidróxido de Alumínio e Magnésio',
    synonymsA: ['Cipro', 'Pricipia'],
    synonymsB: ['Simeco Plus', 'Mylanta', 'Pepsamar'],
    severity: 'Moderada',
    category: 'Infectologia / Gastroenterologia',
    mechanism: 'Cátions polivalentes (Al3+, Mg2+, Ca2+, Fe2+) formam quelatos insolúveis com a fluorquinolona no trato gastrointestinal.',
    effect: 'Diminuição de até 90% na absorção do Ciprofloxacino, levando à falha do tratamento antimicrobiano e desenvolvimento de resistência bacteriana.',
    recommendation: 'Administrar o Ciprofloxacino pelo menos 2 horas antes ou 6 horas depois de tomar antiácidos.',
    alternatives: 'Inibidores da bomba de prótons administrados separadamente, se o objetivo for controle de acidez.',
    foodInteractions: 'Leite e derivados lácteos (ricos em cálcio) também devem ser espaçados em 2 horas.',
    riskScore: 6,
    affectedOrgans: ['Trato Gastrointestinal', 'Absorção Sistêmica']
  },
  {
    drugA: 'Lítio (Carbonato de Lítio)',
    drugB: 'Hidroclorotiazida',
    synonymsA: ['Carbolitium'],
    synonymsB: ['Clorana', 'Drenidra'],
    severity: 'Grave',
    category: 'Psiquiatria / Nefrologia',
    mechanism: 'A Hidroclorotiazida induz natriurese nos túbulos renais. A depleção de sódio faz o rim reabsorver compensatoriamente o Lítio.',
    effect: 'Elevação substancial da litemia com toxicidade grave por Lítio: tremores grosseiros, ataxia, letargia, convulsões e coma.',
    recommendation: 'Monitorar litemia semanalmente se a combinação for inevitável e reduzir a dose de Lítio em 25% a 50%.',
    alternatives: 'Diuréticos poupadores de potássio ou Bloqueadores de Canal de Cálcio sob rigorosa monitorização.',
    foodInteractions: 'Dietas hipossódicas rígidas pioram vertiginosamente a retenção de Lítio.',
    riskScore: 9,
    affectedOrgans: ['Sistema Nervoso Central', 'Rins']
  },
  {
    drugA: 'Levotiroxina',
    drugB: 'Carbonato de Cálcio / Sulfato Ferroso',
    synonymsA: ['Puran T4', 'Levoid', 'Euthyrox'],
    synonymsB: ['Os-Cal', 'Noripurum', 'Combiron'],
    severity: 'Moderada',
    category: 'Endocrinologia / Hematologia',
    mechanism: 'O Cálcio e o Ferro ligam-se à Levotiroxina no estômago formando complexos insolúveis de difícil absorção.',
    effect: 'Redução expressiva na eficácia da hormona tiroidiana, resultando em sintomas persistentes de hipotireoidismo.',
    recommendation: 'Tomar a Levotiroxina em jejum pela manhã e aguardar no mínimo 4 horas para ingerir suplementos de Cálcio ou Ferro.',
    alternatives: 'Adequação rigorosa de horários.',
    foodInteractions: 'Café, fibras e leite ingeridos junto com a Levotiroxina diminuem sua bioabsorção.',
    riskScore: 5,
    affectedOrgans: ['Tireoide', 'Metabolismo Geral']
  },
  {
    drugA: 'Digoxina',
    drugB: 'Amiodarona',
    synonymsA: ['Digoxina Teuto', 'Lanoxin'],
    synonymsB: ['Ancoron', 'Atlantil'],
    severity: 'Grave',
    category: 'Cardiologia',
    mechanism: 'A Amiodarona inibe a P-glicoproteína renal e hepática responsável pelo clearance de Digoxina.',
    effect: 'Aumento de 70% a 100% nas concentrações plasmáticas de Digoxina com risco de toxicidade digitálica (náuseas, visão amarelada/halos, bradicardia grave e arritmias cardíacas letais).',
    recommendation: 'Reduzir a dose de Digoxina pela metade ao iniciar Amiodarona e dosar digoxinemia regularmente.',
    alternatives: 'Betabloqueadores sob estrito controle para manejo de frequência cardíaca.',
    foodInteractions: 'Fibras em excesso reduzem absorção inicial da Digoxina.',
    riskScore: 9,
    affectedOrgans: ['Coração', 'Visão']
  },
  {
    drugA: 'Amoxicilina',
    drugB: 'Alopurinol',
    synonymsA: ['Amoxil', 'Novocilin'],
    synonymsB: ['Zyloric', 'Alopurinol Teuto'],
    severity: 'Moderada',
    category: 'Infectologia / Reumatologia',
    mechanism: 'Mecanismo imunomediado não completamente elucidado que potencializa a reatividade cutânea à aminopenicilina.',
    effect: 'Frequência nitidamente elevada de exantema maculopapular e reações alérgicas dermatológicas severas.',
    recommendation: 'Monitorar sinais de rash cutâneo. Se surgir erupção, interromper os medicamentos e avaliar etiologia.',
    alternatives: 'Cefalosporinas orais (Cefalexina/Cefuroxima) como alternativa antibiótica quando viável.',
    foodInteractions: 'Sem interação nutricional direta significativa.',
    riskScore: 5,
    affectedOrgans: ['Pele (Sistema Tegumentar)']
  },
  {
    drugA: 'Carbamazepina',
    drugB: 'Dexametasona',
    synonymsA: ['Tegretol'],
    synonymsB: ['Decadron'],
    severity: 'Moderada',
    category: 'Neurologia / Endocrinologia',
    mechanism: 'A Carbamazepina é um potente indutor do sistema microssomal CYP3A4 no fígado, acelerando a degradação de corticoides.',
    effect: 'Queda drástica dos níveis terapêuticos da Dexametasona/Prednisona, com perda do efeito anti-inflamatório ou imunossupressor.',
    recommendation: 'Monitorar resposta clínica. Pode ser necessário dobrar ou triplicar a dose do corticoide durante a coadministração.',
    alternatives: 'Valproato de Sódio ou Levetiracetam como anticonvulsivantes sem forte indução enzimática.',
    foodInteractions: 'Suco de toranja inibe a eliminação da Carbamazepina.',
    riskScore: 6,
    affectedOrgans: ['Fígado', 'Sistema Imunológico']
  },
  {
    drugA: 'Metotrexato',
    drugB: 'Aspirina (Ácido Acetilsalicílico)',
    synonymsA: ['Miotrex', 'Metoject'],
    synonymsB: ['AAS'],
    severity: 'Grave',
    category: 'Reumatologia / Oncologia',
    mechanism: 'A Salicilina desloca o Metotrexato das proteínas plasmáticas e inibe sua secreção tubular renal.',
    effect: 'Toxicidade sistêmica grave por Metotrexato: mielossupressão (leucopenia, anemia, trombocitopenia), estomatite e toxicidade hepática.',
    recommendation: 'Evitar o uso concomitante de AAS em doses analgésicas/anti-inflamatórias durante esquemas com Metotrexato.',
    alternatives: 'Paracetamol para dor eventual.',
    foodInteractions: 'Álcool aumenta drasticamente o risco de fibrose e cirrose hepática por Metotrexato.',
    riskScore: 9,
    affectedOrgans: ['Medula Óssea', 'Fígado', 'Rins']
  },
  {
    drugA: 'Dipirona (Metamizol)',
    drugB: 'Clorpromazina',
    synonymsA: ['Novalgina', 'Anador'],
    synonymsB: ['Amplictil'],
    severity: 'Moderada',
    category: 'Analgesia / Psiquiatria',
    mechanism: 'Interação no centro termorregulador hipotalâmico e inibição central aditiva.',
    effect: 'Risco de hipotermia severa e imprevisível.',
    recommendation: 'Evitar o uso concomitante em idosos ou pacientes em UTIs. Monitorar temperatura corporal.',
    alternatives: 'Paracetamol em doses adequadas.',
    foodInteractions: 'Álcool intensifica sedação.',
    riskScore: 5,
    affectedOrgans: ['Termorregulação (Cérebro)']
  },
  {
    drugA: 'Azitromicina',
    drugB: 'Haloperidol',
    synonymsA: ['Astro', 'Azitrophar'],
    synonymsB: ['Haldol'],
    severity: 'Grave',
    category: 'Infectologia / Psiquiatria',
    mechanism: 'Bloqueio aditivo dos canais de potássio IKr no miocárdio.',
    effect: 'Prolongamento do intervalo QTc no eletrocardiograma com risco iminente de Torsades de Pointes (arritmia ventricular fatal).',
    recommendation: 'Evitar associação em pacientes com síndrome do QT longo prévia, bradicardia ou distúrbios eletrolíticos.',
    alternatives: 'Amoxicilina/Clavulanato para infecções bacterianas susceptíveis sem impacto no QT.',
    foodInteractions: 'Evitar cafeína e energéticos em excesso para não agravar arritmias.',
    riskScore: 9,
    affectedOrgans: ['Coração (Eletrofisiologia)']
  },
  {
    drugA: 'Rivaroxabana',
    drugB: 'Cetoconazol',
    synonymsA: ['Xarelto'],
    synonymsB: ['Nizoral', 'CetoMed'],
    severity: 'Grave',
    category: 'Hematologia / Dermatologia / Infectologia',
    mechanism: 'O Cetoconazol é um inibidor combinado potente do CYP3A4 e da P-glicoproteína (P-gp).',
    effect: 'Aumento de mais de 150% na AUC da Rivaroxabana, provocando sangramentos graves e imprevisíveis.',
    recommendation: 'Uso concomitante de Cetoconazol, Itraconazol ou Ritonavir com Rivaroxabana é contraindicado.',
    alternatives: 'Antifúngicos sem inibição expressiva (ex: Terbinafina tópica ou Fluconazol em menor dose sob estrita vigilância).',
    foodInteractions: 'Tomar a Rivaroxabana (doses 15/20mg) sempre com alimentos para garantir absorção adequada.',
    riskScore: 9,
    affectedOrgans: ['Sistema Coagulação', 'Fígado']
  },
  {
    drugA: 'Lorazepam',
    drugB: 'Álcool Etílico',
    synonymsA: ['Loram', 'Ansitec (diferente)', 'Ativan'],
    synonymsB: ['Bebidas Alcoólicas'],
    severity: 'Grave',
    category: 'Psiquiatria / Toxicologia',
    mechanism: 'Potencialização alostérica sinérgica nos receptores GABA-A no sistema nervoso central.',
    effect: 'Depressão respiratória grave, coma, sedação profunda, amnésia anterógrada e risco de óbito.',
    recommendation: 'Orientação absoluta ao paciente sobre a proibição do consumo de álcool durante tratamento com benzodiazepínicos.',
    alternatives: 'Tratamentos não farmacológicos para ansiedade ou transição terapêutica.',
    foodInteractions: 'Álcool em qualquer quantidade é estritamente proibidíssimo.',
    riskScore: 10,
    affectedOrgans: ['Sistema Nervoso Central', 'Pulmões (Drive Respiratório)']
  },
  {
    drugA: 'Propranolol',
    drugB: 'Insulina NPH',
    synonymsA: ['Inderal'],
    synonymsB: ['Humulin N', 'Novolin N'],
    severity: 'Moderada',
    category: 'Cardiologia / Endocrinologia',
    mechanism: 'O betabloqueador não seletivo bloqueia a resposta adrenérgica compensatória disparada durante eventos de hipoglicemia.',
    effect: 'Mascaramento dos sintomas de alerta de hipoglicemia (como taquicardia e tremores). Apenas a sudorese profusa permanece como sinal.',
    recommendation: 'Instruir o paciente diabético sobre a sudorese como sinal primário de hipoglicemia e priorizar betabloqueadores cardioseletivos.',
    alternatives: 'Atenolol ou Metoprolol (cardioseletivos beta-1).',
    foodInteractions: 'Alimentação irregular aumenta o risco imprevisível de hipoglicemia.',
    riskScore: 6,
    affectedOrgans: ['Sistema Nervoso Autônomo', 'Glicemia']
  },
  {
    drugA: 'Gabapentina',
    drugB: 'Morfina',
    synonymsA: ['Neurontin', 'Progresse'],
    synonymsB: ['Dimorf'],
    severity: 'Moderada',
    category: 'Neurologia / Anestesiologia',
    mechanism: 'A Morfina aumenta a absorção da Gabapentina e ambos possuem efeito depressor central complementar.',
    effect: 'Aumento da frequência de sonolência profunda, tonturas, ataxia e depressão respiratória moderada a severa.',
    recommendation: 'Monitorar atentamente o estado de alerta do paciente e reduzir as doses iniciais de ambos os medicamentos.',
    alternatives: 'Ajuste posológico progressivo e individualizado.',
    foodInteractions: 'Evitar bebidas alcoólicas e sedativos naturais (valeriana).',
    riskScore: 7,
    affectedOrgans: ['Sistema Nervoso Central', 'Sistema Respiratório']
  },
  {
    drugA: 'Furosemida',
    drugB: 'Gentamicina',
    synonymsA: ['Lasix'],
    synonymsB: ['Garamicina'],
    severity: 'Grave',
    category: 'Nefrologia / Infectologia',
    mechanism: 'Sumação de lesão direta às células ciliadas da cóclea e dobras dos túbulos renais proximal e distal.',
    effect: 'Ototoxicidade irreversível (perda auditiva e zumbido permanente) e insuficiência renal aguda nefrótica.',
    recommendation: 'Evitar associação sempre que possível. Caso seja mandatório, monitorar função renal diária e realizar audiometria.',
    alternatives: 'Utilizar antibióticos não aminoglicosídeos (ex: Cefalosporinas de 3ª geração).',
    foodInteractions: 'Manter hidratação adequada sob orientação médica.',
    riskScore: 9,
    affectedOrgans: ['Ouvido Interno (Auditivo)', 'Rins']
  },
  {
    drugA: 'Sildenafil',
    drugB: 'Isossorbida (Mononitrato / Dinitrato)',
    synonymsA: ['Viagra'],
    synonymsB: ['Isordil', 'Monocordil'],
    severity: 'Grave',
    category: 'Cardiologia / Urologia (CONTRAINDICAÇÃO ABSOLUTA)',
    mechanism: 'O nitrato gera óxido nítrico e o Sildenafil impede a degradação do GMPc. Acúmulo maciço de GMPc na musculatura lisa vascular.',
    effect: 'Colapso circulatório fatal, hipotensão refratária profunda e infarto agudo do miocárdio.',
    recommendation: 'Combinação absolutamente CONTRAINDICADA. Deve haver intervalo mínimo de 24h (Sildenafil) ou 48h (Tadalafila) após uso antes de administrar nitratos.',
    alternatives: 'Manejo de angina com betabloqueadores ou estenose vascular sem nitratos.',
    foodInteractions: 'Álcool exacerba o colapso vascular.',
    riskScore: 10,
    affectedOrgans: ['Sistema Cardiovascular Complícito']
  },
  {
    drugA: 'Aspirina (Ácido Acetilsalicílico)',
    drugB: 'Ibuprofeno',
    synonymsA: ['AAS Cardio'],
    synonymsB: ['Advil', 'Alivium'],
    severity: 'Moderada',
    category: 'Cardiologia / Reumatologia',
    mechanism: 'O Ibuprofeno liga-se competitivamente ao sítio de acetilação da COX-1 nas plaquetas, impedindo a ligação irreversível do AAS.',
    effect: 'Perda do efeito cardioprotetor antiagregante da Aspirina, aumentando risco de eventos tromboembólicos coronarianos.',
    recommendation: 'Tomar o AAS pelo menos 30 minutos a 2 horas ANTES do Ibuprofeno, ou 8 horas APÓS.',
    alternatives: 'Paracetamol para dor casual em cardiopatas usando AAS.',
    foodInteractions: 'Tomar com refeição para abrandar irritação gástrica.',
    riskScore: 6,
    affectedOrgans: ['Plaquetas Sangüíneas', 'Coração']
  },
  {
    drugA: 'Metoclopramida',
    drugB: 'Risperidona',
    synonymsA: ['Plasil'],
    synonymsB: ['Risperdal', 'Zargus'],
    severity: 'Moderada',
    category: 'Gastroenterologia / Psiquiatria',
    mechanism: 'Ambos os fármacos são antagonistas potentes dos receptores dopaminérgicos D2 no cérebro.',
    effect: 'Aumento expressivo na incidência de reações extrapiramidais (acatisia, distonia aguda, parkinsonismo medicamentoso e discinesia tardia).',
    recommendation: 'Evitar o uso de Metoclopramida em pacientes em uso de antipsicóticos. Utilizar antieméticos alternativos.',
    alternatives: 'Ondansetrona (Aredia/Vonau) como antiemético de escolha por atuar em receptores de serotonina 5-HT3.',
    foodInteractions: 'Sem interação alimentar direta.',
    riskScore: 6,
    affectedOrgans: ['Sistema Extrapyramidal (SNC)']
  },
  {
    drugA: 'Espironolactona',
    drugB: 'Losartana',
    synonymsA: ['Aldactone'],
    synonymsB: ['Aradois', 'Cozaar'],
    severity: 'Moderada',
    category: 'Cardiologia / Nefrologia',
    mechanism: 'Inibição combinada do eixo renina-angiotensina-aldosterona levando à retenção de potássio pelos rins.',
    effect: 'Risco de hipercalemia (potássio elevado no sangue) e hipotensão postural.',
    recommendation: 'Avaliar dosagem de K+ e creatinina antes e durante o tratamento. Dosagem de potássio superior a 5,5 mEq/L exige interrupção.',
    alternatives: 'Inclusão de diurético tiazídico em dose baixa para equilibrar o potássio, se indicado.',
    foodInteractions: 'Evitar sais dietéticos enriquecidos com Potássio.',
    riskScore: 6,
    affectedOrgans: ['Rins', 'Eletrocardiograma']
  },
  {
    drugA: 'Duloxetina',
    drugB: 'Erva de São João (Hypericum perforatum)',
    synonymsA: ['Cymbalta', 'Velija'],
    synonymsB: ['Hipericão', 'Fitoterápico Calmante'],
    severity: 'Grave',
    category: 'Psiquiatria / Fitoterapia',
    mechanism: 'Superposição de inibição da recaptação de serotonina e noradrenalina pelo fitoterápico e o antidepressivo.',
    effect: 'Desenvolvimento repentino de Síndrome Serotoninérgica com agitação motora, alucinações, taquicardia e picos pressóricos.',
    recommendation: 'Interromper o uso de Hypericum antes de iniciar tratamentos antidepressivos de prescrição.',
    alternatives: 'Manter monoterapia com acompanhamento psiquiátrico.',
    foodInteractions: 'Suplementos estimulantes devem ser totalmente evitados.',
    riskScore: 9,
    affectedOrgans: ['Sistema Nervoso Central', 'Pressão Arterial']
  },
  {
    drugA: 'Verapamil',
    drugB: 'Atenolol',
    synonymsA: ['Dilacoron'],
    synonymsB: ['Atenol', 'Ablok'],
    severity: 'Grave',
    category: 'Cardiologia',
    mechanism: 'Efeito inotrópico e dromotrópico negativo aditivo acentuado sobre o nó sinoatrial e nó atrioventricular.',
    effect: 'Bradicardia extrema (< 40 bpm), bloqueio atrioventricular total, hipotensão e insuficiência cardíaca aguda congestiva.',
    recommendation: 'Evitar combinação intravenosa ou oral. Preferir diidropiridinas (Anlodipino) caso um bloqueador de canal de cálcio seja estritamente necessário junto ao betabloqueador.',
    alternatives: 'Anlodipino + Betabloqueador sob vigilância.',
    foodInteractions: 'Evitar consumo de suco de toranja (grapefruit).',
    riskScore: 9,
    affectedOrgans: ['Sistema de Condução Cardiaco']
  },
  {
    drugA: 'Captopril',
    drugB: 'Alisquireno',
    synonymsA: ['Capoten'],
    synonymsB: ['Rasilez'],
    severity: 'Grave',
    category: 'Cardiologia / Nefrologia',
    mechanism: 'Duplo bloqueio direto da cascata renina-angiotensina-aldosterona.',
    effect: 'Aumento significativo na frequência de hipotensão severa, hipercalemia e insuficiência renal aguda refratária.',
    recommendation: 'Bloqueio duplo do SRAA é formalmente desaconselhado pelas diretrizes de cardiologia.',
    alternatives: 'Manter apenas um agente modulador do SRAA com posologia ajustada.',
    foodInteractions: 'Alimentos reduzem a absorção do Captopril; deve ser ingerido 1 hora antes das refeições.',
    riskScore: 9,
    affectedOrgans: ['Rins', 'Pressão Arterial']
  },
  {
    drugA: 'Glimepirida',
    drugB: 'Miconazol (Gel Oral / Tópico Oral)',
    synonymsA: ['Amaryl'],
    synonymsB: ['Daktarin Gel Oral'],
    severity: 'Grave',
    category: 'Endocrinologia / Odontologia / Dermatologia',
    mechanism: 'O Miconazol inibe a isoenzima CYP2C9, bloqueando a eliminação da sulfonilureia.',
    effect: 'Hipoglicemia grave e prolongada com rebaixamento do nível de consciência, sudorese fria e risco de danos cerebrais.',
    recommendation: 'Substituir o Miconazol por Nistatina suspensão para tratamento de candidíase oral em usuários de sulfonas antidiabéticas.',
    alternatives: 'Nistatina em suspensão oral.',
    foodInteractions: 'Jejum prolongado acentua exponencialmente a crise hipoglicêmica.',
    riskScore: 9,
    affectedOrgans: ['Pâncreas', 'Cérebro', 'Fígado']
  },
  {
    drugA: 'Hidroxicloroquina',
    drugB: 'Fluoxetina',
    synonymsA: ['Reuquinol', 'Plaquenil'],
    synonymsB: ['Prozac', 'Daforin'],
    severity: 'Grave',
    category: 'Reumatologia / Psiquiatria / Cardiologia',
    mechanism: 'Ambos os fármacos possuem propriedades de prolongamento do intervalo QTc no eletrocardiograma e inibição metabólica hepática via CYP2D6.',
    effect: 'Risco significativamente aumentado de arritmias ventriculares graves (Torsades de Pointes), palpitações e síncope.',
    recommendation: 'Monitorar EKG (intervalo QTc) de forma regular. Considerar ajustar dose da Fluoxetina ou substituir por antidepressivo de menor impacto cardíaco.',
    alternatives: 'Sertralina ou Escitalopram em doses baixas sob monitorização eletrocardiográfica.',
    foodInteractions: 'Evitar consumo excessivo de álcool e estimulantes que possam induzir taquicardia.',
    riskScore: 9,
    affectedOrgans: ['Coração (Eletrofisiologia)', 'Fígado', 'Sistema Nervoso Central']
  },
  {
    drugA: 'Hidroxicloroquina',
    drugB: 'Azitromicina',
    synonymsA: ['Reuquinol', 'Plaquenil'],
    synonymsB: ['Astro', 'Azitrophar'],
    severity: 'Grave',
    category: 'Reumatologia / Infectologia / Cardiologia',
    mechanism: 'Efeito aditivo e sinérgico de prolongamento da repolarização ventricular e bloqueio do intervalo QTc.',
    effect: 'Risco de parada cardíaca, arritmia ventricular fatal (Torsades de Pointes) e elevação de episódios hipoglicêmicos.',
    recommendation: 'Associação formalmente desaconselhada exceto em protocolos de exceção com rigorosa monitorização eletrocardiográfica diária.',
    alternatives: 'Uso de antibióticos alternativos sem impacto significativo na repolarização miocárdica (ex: Amoxicilina).',
    foodInteractions: 'Manter bom aporte de potássio e magnésio para estabilizar membrana cardíaca.',
    riskScore: 10,
    affectedOrgans: ['Coração (Sistema de Condução Visual e Elétrico)']
  }
];
